### ISSUE TITLE
歌单只能下载10首歌？

### ISSUE THREAD

**Issue by aalavender** [anjia0532/netease_download#15]

**Comment by anjia0532** [comment]
没有限制，请贴出你下载的歌单

**Comment by aalavender** [comment]
https://music.163.com/playlist?id=7501889&userid=448473883

**Comment by anjia0532** [comment]
应该是网易云改了api了，做了限制了，网页端只允许下载10首，登录后，只允许20首。

**Comment by anjia0532** [comment]
你可以试试别的框架 https://github.com/p697/cloudmusic
