### ISSUE TITLE
能批量下载.csv文件数据的链接吗

### ISSUE THREAD

**Issue by vinyo** [anjia0532/netease_download#5]
https://music.163.com/#/song?id=28987626
https://music.163.com/#/song?id=28987626
https://music.163.com/#/song?id=28987626
https://music.163.com/#/song?id=28987626
如这些数据

**Comment by anjia0532** [comment]
你可以自己建立一个歌单，用歌单形式下载。在那时不支持csv。如果你会py的话，也可以自己扩展，也比较简单，最low的，读csv，写个循环，重复调用main.py就行了
