### ISSUE TITLE
下排行榜出错

### ISSUE THREAD

**Issue by vinyo** [anjia0532/netease_download#6]
++ ▒▒▒▒▒▒▒▒: #11/100# Lemon - ▒׽▒▒▒▒▒.mp3
  ++ mp3_quality: High

  ++ ▒▒▒▒▒▒▒▒: #12/100# ▒▒▒▒ - ▒▒▒.mp3
  ++ mp3_quality: High

  ++ ▒▒▒▒▒▒▒▒: #13/100# Three Pass (Live) - ▒▒▒▒▒▒▒LIL-EM & ICE.mp3
  ++ mp3_quality: High

  ++ ▒▒▒▒▒▒▒▒: #14/100# ▒▒ӥ󥰥ǥå▒ - amazarashi.mp3
  ++ mp3_quality: High
Traceback (most recent call last):
  File "main.py", line 450, in <module>
    main(args.url)
  File "main.py", line 432, in main
    x.url_parser(url)
  File "main.py", line 427, in url_parser
    self.download()
  File "main.py", line 374, in download
    % (n or ii, amount_songs, col,s % (1, 91, mp3_quality)))
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 33: illegal multibyte sequence

**Comment by anjia0532** [comment]
发一下链接

**Comment by anjia0532** [comment]
怀疑是 #4 类似的问题，你有没有下载很大量的歌曲？

**Comment by anjia0532** [comment]
经过试验，`python main.py https://music.163.com/#/discover/toplist?id=3779629` 是可以的
