### ISSUE TITLE
mp3文件的名字有时候是“歌手-歌曲”有时候是“歌曲-歌手”

### ISSUE THREAD

**Issue by I-love-study** [anjia0532/netease_download#7]
mp3文件的名字有时候是“歌手-歌曲”有时候是“歌曲-歌手”。明明id3都没错就是这里会出现问题。是否能创建一个变量能调节这个名字的问题

**Comment by anjia0532** [comment]
能发个示例连接么，我看看

**Comment by anjia0532** [comment]
命名都是 `歌曲名-歌手名.mp3`
https://github.com/anjia0532/netease_download/blob/463a938680a65b8736f89d708748ad7066158c6c/main.py#L210-L213

**Comment by I-love-study** [comment]
![_20181223170614](https://user-images.githubusercontent.com/39652142/50382219-3c3de200-06d5-11e9-9273-94783535c1db.png)
就比如这个

**Comment by anjia0532** [comment]
你给我链接啊，你有没有对比网易云音乐的页面上的内容，是对的么？

**Comment by I-love-study** [comment]
好吧😂我看错了。歌名和歌手名实在是太像了。实在抱歉
